on:
  push:
    branches:
      - master
      - dev
  #pull_request:
  #  branches:
  #    - master
  #schedule:
    # * is a special character in YAML so we have to quote this string
    # 3am Pacific = 11am UTC
    # https://crontab.guru is your friend
  #  - cron:  '0 17 * * *'

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
